name: .NET Build and Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Run
        working-directory: adventOfCode23
        run: dotnet run --ci

